# Generated by Django 5.0.6 on 2025-08-26 04:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='opinion',
            old_name='aprobada',
            new_name='aprobado',
        ),
        migrations.AddField(
            model_name='opinion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='calificacion',
            field=models.IntegerField(help_text='Calificación del 1 al 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='principal.casa'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='comentario',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='opinion',
            unique_together={('casa', 'usuario')},
        ),
    ]
